// Geographic labels for the 3D terrain view. Every label is anchored to a REAL lon/lat and re-projected through
// the three.js camera on every rendered frame, so it moves with the terrain. No fixed screen positions.
//
// Sources (nothing invented):
//   * place_labels.json -- OpenStreetMap localities, stations and parks inside the DEM (generated by
//     backend/floodnet/data/place_labels.py; ODbL, (c) OpenStreetMap contributors);
//   * the road network the app already loads (GET /api/roads, also OSM): trunk / primary road names, and the
//     named circles (junctions), placed at the midpoint of that name's longest segment.
import { lonLatToGrid, surfaceAt, drawnHeight } from './dem.js'

// placement priority: a higher rank wins a collision. Roads rank below localities and above minor landmarks.
const ROAD_RANK = { trunk: 62, primary: 52 }
const JUNCTION_RANK = 66

function segLength(coords) {
  let d = 0
  for (let i = 1; i < coords.length; i += 1) d += Math.hypot(coords[i][0] - coords[i - 1][0], coords[i][1] - coords[i - 1][1])
  return d
}

/** Point at half the length of a polyline, plus a short span around it (for the label's direction). */
export function alongMidpoint(coords) {
  const total = segLength(coords)
  let acc = 0
  for (let i = 1; i < coords.length; i += 1) {
    const [x0, y0] = coords[i - 1]; const [x1, y1] = coords[i]
    const d = Math.hypot(x1 - x0, y1 - y0)
    if (acc + d >= total / 2 && d > 0) {
      const t = (total / 2 - acc) / d
      return { at: [x0 + (x1 - x0) * t, y0 + (y1 - y0) * t], from: [x0, y0], to: [x1, y1] }
    }
    acc += d
  }
  const [a] = coords
  return { at: a, from: a, to: coords[coords.length - 1] || a }
}

/** One label per trunk/primary road NAME (and per named circle), from the road FeatureCollection. */
export function roadLabels(roadsFc) {
  const byName = new Map()
  for (const f of roadsFc?.features || []) {
    const p = f.properties || {}
    const coords = f.geometry?.type === 'LineString' ? f.geometry.coordinates : null
    if (!p.name || !coords || coords.length < 2 || !(p.highway in ROAD_RANK)) continue
    const len = segLength(coords)
    const prev = byName.get(p.name)
    if (!prev || len > prev.len) byName.set(p.name, { name: p.name, highway: p.highway, coords, len })
  }
  return [...byName.values()].map(({ name, highway, coords }) => {
    const junction = /circle$/i.test(name)
    const { at, from, to } = alongMidpoint(coords)
    return {
      name, tier: junction ? 'junction' : 'road', kind: highway,
      rank: junction ? JUNCTION_RANK : ROAD_RANK[highway], lon: at[0], lat: at[1],
      dir: junction ? null : [from, to],
    }
  })
}

/** All labels in the DEM's metre frame. Road labels whose name duplicates a place label are dropped. */
export function buildLabels(dem, roadsFc, places) {
  const placeNames = new Set(places.map((p) => p.name.toLowerCase()))
  const all = [...places, ...roadLabels(roadsFc).filter((r) => !placeNames.has(r.name.toLowerCase()))]
  const inside = (x, y) => x >= 0 && y >= 0 && x <= dem.widthM && y <= dem.heightM
  return all
    .map((l, i) => {
      const [x, y] = lonLatToGrid(dem, l.lon, l.lat)
      const dir = l.dir ? l.dir.map(([lon, lat]) => lonLatToGrid(dem, lon, lat)) : null
      return { id: `${l.tier}:${i}`, text: l.name, tier: l.tier, kind: l.kind, rank: l.rank, x, y, dir }
    })
    .filter((l) => inside(l.x, l.y))
    .sort((a, b) => b.rank - a.rank)
}

/** Greedy placement in rank order: a label is shown only if its screen box overlaps no shown label and no
 *  pre-placed obstacle (FloodNet overlays such as flood-spot pins, which always take precedence). */
export function layoutLabels(items, pad = 4, obstacles = []) {
  const shown = [...obstacles]
  for (const it of items) {
    if (!it.visible) continue
    const box = [it.sx - it.w / 2 - pad, it.sy - it.h / 2 - pad, it.sx + it.w / 2 + pad, it.sy + it.h / 2 + pad]
    if (shown.some((b) => box[0] < b[2] && box[2] > b[0] && box[1] < b[3] && box[3] > b[1])) continue
    shown.push(box)
    it.show = true
  }
  return items
}

/** True if the terrain rises above the straight line from the camera to the anchor (heightfield ray march). */
export function occluded(dem, relief, cam, p, steps = 28) {
  for (let s = 1; s < steps; s += 1) {
    const t = s / steps
    const x = cam.x + (p.x - cam.x) * t
    const y = cam.y + (p.y - cam.y) * t
    if (x < 0 || y < 0 || x > dem.widthM || y > dem.heightM) continue
    const ground = drawnHeight(dem, surfaceAt(dem, x, y), relief)
    if (ground > cam.z + (p.z - cam.z) * t + 2) return true
  }
  return false
}

// ---------------------------------------------------------------- DOM layer (driven by the renderer)
const LIFT_M = 4                           // anchor a few metres above the drawn ground so it never sinks into it

export class LabelLayer {
  constructor(host, labels, classes) {
    this.host = host
    this.items = labels.map((l) => {
      const el = document.createElement('div')
      el.className = `${classes.label} ${classes[l.tier] || ''} ${l.kind === 'station' ? classes.station || '' : ''}`
      el.textContent = l.text
      el.style.visibility = 'hidden'
      host.appendChild(el)
      return { ...l, el, w: 0, h: 0 }
    })
    this.measured = false
  }

  /** `obstacles`: screen boxes labels must avoid (flood-spot pins). `isCovered(x, y)`: true where UI (panels,
   *  toolbars) lies over the map -- a label is shown only where its centre and both ends are uncovered. */
  update(THREE, camera, dem, relief, width, height, obstacles = [], isCovered = null) {
    if (!this.items.length || !width || !height) return
    if (!this.measured) {
      for (const it of this.items) { it.w = it.el.offsetWidth; it.h = it.el.offsetHeight }
      this.measured = this.items.every((it) => it.w > 0)
    }
    const v = new THREE.Vector3()
    const cam = camera.position
    for (const it of this.items) {
      const z = drawnHeight(dem, surfaceAt(dem, it.x, it.y), relief) + LIFT_M
      v.set(it.x, it.y, z).project(camera)
      it.visible = v.z > -1 && v.z < 1 && Math.abs(v.x) < 1.05 && Math.abs(v.y) < 1.05
      if (!it.visible) continue
      it.sx = (v.x * 0.5 + 0.5) * width
      it.sy = (-v.y * 0.5 + 0.5) * height
      it.angle = 0
      if (it.dir) {                          // road names follow the road's on-screen direction, kept upright
        const a = new THREE.Vector3(it.dir[0][0], it.dir[0][1], z).project(camera)
        const b = new THREE.Vector3(it.dir[1][0], it.dir[1][1], z).project(camera)
        let ang = Math.atan2(-(b.y - a.y) * height, (b.x - a.x) * width) * (180 / Math.PI)
        if (ang > 90) ang -= 180
        if (ang < -90) ang += 180
        it.angle = ang
      }
      const rad = Math.abs(it.angle) * (Math.PI / 180)
      it.bw = it.w * Math.cos(rad) + it.h * Math.sin(rad)
      it.bh = it.w * Math.sin(rad) + it.h * Math.cos(rad)
      it.visible = !occluded(dem, relief, cam, { x: it.x, y: it.y, z })
      if (it.visible && isCovered) {
        const half = Math.max(it.bw / 2 - 2, 0)
        it.visible = !(isCovered(it.sx, it.sy) || isCovered(it.sx - half, it.sy) || isCovered(it.sx + half, it.sy))
      }
    }
    // collide on the screen box of the ROTATED label; items are already in rank order
    const boxes = layoutLabels(this.items.map((it) => ({ visible: it.visible, sx: it.sx, sy: it.sy, w: it.bw, h: it.bh })), 4, obstacles)
    this.items.forEach((it, k) => {
      it.show = Boolean(boxes[k].show)
      if (!it.show) { it.el.style.visibility = 'hidden'; return }
      it.el.style.visibility = 'visible'
      it.el.style.transform = `translate(${Math.round(it.sx)}px, ${Math.round(it.sy)}px) translate(-50%, -50%) rotate(${it.angle.toFixed(1)}deg)`
    })
  }

  dispose() {
    for (const it of this.items) it.el.remove()
    this.items = []
  }
}

/** FloodNet point overlays (MCGM known flood spots) projected like the labels, but never dropped by collisions:
 *  they rank above geographic labels. `points` = [{ x, y, active, title }] in the DEM metre frame. */
export class PinLayer {
  constructor(host, points, classes) {
    this.items = points.map((p) => {
      const el = document.createElement('div')
      el.className = `${classes.pin} ${p.active ? '' : classes.pinInactive || ''}`
      el.title = p.title
      el.style.visibility = 'hidden'
      host.appendChild(el)
      return { ...p, el }
    })
  }

  /** Positions the pins; returns their screen boxes so labels can keep clear of them. */
  update(THREE, camera, dem, relief, width, height) {
    const v = new THREE.Vector3()
    const boxes = []
    for (const it of this.items) {
      const z = drawnHeight(dem, surfaceAt(dem, it.x, it.y), relief) + LIFT_M
      v.set(it.x, it.y, z).project(camera)
      const onScreen = v.z > -1 && v.z < 1 && Math.abs(v.x) < 1 && Math.abs(v.y) < 1
      if (!onScreen || occluded(dem, relief, camera.position, { x: it.x, y: it.y, z })) {
        it.el.style.visibility = 'hidden'
        continue
      }
      const sx = (v.x * 0.5 + 0.5) * width
      const sy = (-v.y * 0.5 + 0.5) * height
      it.el.style.visibility = 'visible'
      it.el.style.transform = `translate(${Math.round(sx)}px, ${Math.round(sy)}px) translate(-50%, -50%)`
      boxes.push([sx - 7, sy - 7, sx + 7, sy + 7])
    }
    return boxes
  }

  dispose() {
    for (const it of this.items) it.el.remove()
    this.items = []
  }
}
